export const Actions = {
  PRODUCT_LIST     : 'PRODUCT_LIST',
  ADD_NEW_PRODUCT  : 'ADD_NEW_PRODUCT',
  ADD_TO_CART      : 'ADD_TO_CART',
  REMOVE_FROM_CART : 'REMOVE_FROM_CART',
  UPDATE_CART      : 'UPDATE_CART'
};
